plugins {
    id 'application'
    id 'com.google.protobuf'
}

application {
    mainClass = 'clients.Producer'
}

dependencies {
    implementation libs.kafka.protobuf.serializer
    implementation libs.protobuf.java
}

// The User class is generated at build time from the one shared schema
sourceSets.main.proto.srcDir '../proto'

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${libs.versions.protobufJava.get()}" }
}
